apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8
    ports:
    - containerPort: 80
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: ${PWORD}
    - name: MYSQL_DATABASE
      value: brack